apiVersion: v1
kind: DeploymentConfig
metadata:
  annotations:
    openshift.io/generated-by: OpenShiftNewApp
  creationTimestamp: null
  labels:
    app: jboss-greeter
  name: jboss-greeter
spec:
  replicas: 1
  selector:
    app: jboss-greeter
    deploymentconfig: jboss-greeter
  strategy:
    resources: {}
    rollingParams:
      intervalSeconds: 1
      maxSurge: 25%
      maxUnavailable: 25%
      timeoutSeconds: 600
      updatePeriodSeconds: 1
    type: Rolling
  template:
    metadata:
      annotations:
        openshift.io/generated-by: OpenShiftNewApp
      creationTimestamp: null
      labels:
        app: jboss-greeter
        deploymentconfig: jboss-greeter
    spec:
      containers:
      - image: 172.30.195.192:5000/myapp/jboss-greeter@sha256:5804a8ef8c69f582cde24a0339f744632933158e0e866252074089ef7fed1c4e
        imagePullPolicy: Always
        name: jboss-greeter
        env:
        - name: TX_DATABASE_PREFIX_MAPPING
          value: my-oracle=MY
        - name: DB_SERVICE_PREFIX_MAPPING
          value: my-oracle=MY
        - name: MY_USERNAME
          value: system
        - name: MY_PASSWORD
          value: oracle
        - name: MY_MIN_POOL_SIZE
          value: "1"
        - name: MY_MAX_POOL_SIZE
          value: "10"
        - name: MY_TX_ISOLATION
          value: TRANSACTION_READ_COMMITTED
        - name: MY_DATABASE
          value: xe
        - name: HORNETQ_QUEUES
        - name: HORNETQ_TOPICS
        - name: OPENSHIFT_KUBE_PING_LABELS
          value: application=jboss-greeter
        - name: OPENSHIFT_KUBE_PING_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        ports:
        - containerPort: 8080
          protocol: TCP
        - containerPort: 8443
          protocol: TCP
        - containerPort: 8778
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      securityContext: {}
      terminationGracePeriodSeconds: 30
  triggers:
  - type: ConfigChange
  - imageChangeParams:
      automatic: true
      containerNames:
      - jboss-greeter
      from:
        kind: ImageStreamTag
        name: jboss-greeter:latest
    type: ImageChange
status:
  latestVersion: 10
