apiVersion: v1
kind: DeploymentConfig
metadata:
  creationTimestamp: null
  labels:
    application: jboss-greeter
    template: eap64-flyway-s2i
    xpaas: 1.1.0
  name: greeter
spec:
  replicas: 1
  selector:
    deploymentConfig: jboss-greeter
  strategy:
    resources: {}
    type: Rolling
    rollingParams:
      pre:
        failurePolicy: fail
        execNewPod:
          containerName: jboss-greeter
          command:
          - flyway
          - migrate
          - "-locations=/var/git/src/main/resources/sql"
          volumes:
          - git 
  template:
    metadata:
      creationTimestamp: null
      labels:
        application: jboss-greeter
        deploymentConfig: jboss-greeter
      name: jboss-greeter
    spec:
      containers:
      - env:
        - name: TX_DATABASE_PREFIX_MAPPING
          value: my-oracle=MY
        - name: DB_SERVICE_PREFIX_MAPPING
          value: my-oracle=MY
        - name: MY_USERNAME
          value: schemauser
        - name: MY_PASSWORD
          value: password
        - name: MY_MIN_POOL_SIZE
          value: "1"
        - name: MY_MAX_POOL_SIZE
          value: "10"
        - name: MY_TX_ISOLATION
          value: "false"
        - name: MY_DATABASE
          value: schemaname
        - name: HORNETQ_CLUSTER_PASSWORD
          value: U2DKiXkm
        - name: OPENSHIFT_KUBE_PING_LABELS
          value: application=jboss-greeter
        - name: OPENSHIFT_KUBE_PING_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        - name: HORNETQ_QUEUES
        - name: HORNETQ_TOPICS
        image: 172.30.195.192:5000/myapp/jboss-greeter:latest
        imagePullPolicy: Always
        name: jboss-greeter
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        - containerPort: 8888
          name: ping
          protocol: TCP
        readinessProbe:
          exec:
            command:
            - /bin/bash
            - -c
            - /opt/eap/bin/readinessProbe.sh
          timeoutSeconds: 1
        resources: {}
        terminationMessagePath: /dev/termination-log
        volumeMounts:
        - name: flyway-base
          mountPath: /var/git
      volumes:
      - name: flyway-base
        gitRepo:
          repository: "https://github.com/sterburg/jboss-greeter.git"
          revision: master
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      securityContext: {}
      terminationGracePeriodSeconds: 60
  triggers:
  - imageChangeParams:
      automatic: true
      containerNames:
      - jboss-greeter
      from:
        kind: ImageStreamTag
        name: jboss-greeter:latest
    type: ImageChange
  - type: ConfigChange
