apiVersion: v1
kind: List
Items:
  - apiVersion: v1
    kind: Service
    metadata:
      annotations:
        description: Oracle Datasource
      creationTimestamp: null
      labels:
        datasource: oracle
      name: oracle
    spec:
      ports:
      - name: oracle
        port: 1521
        protocol: TCP
        targetPort: 1521
      sessionAffinity: None
      type: ClusterIP
    status:
      loadBalancer: {}
  - apiVersion: v1
    kind: Endpoints
    metadata:
      creationTimestamp: null
      labels:
        datasource: oracle
      name: oracle
    subsets:
    - addresses:
      - ip: 192.168.1.82
      ports:
      - name: oracle
        port: 1521
        protocol: TCP
