CREATE TABLE test_user (
  name VARCHAR(25) NOT NULL,
  PRIMARY KEY(name)
);

INSERT INTO test_user (name) VALUES ('Mr. T');


CREATE TABLE USERS (
  ID        INT          NOT NULL,
  USERNAME  VARCHAR(255) NOT NULL,
  FIRSTNAME VARCHAR(255) NOT NULL,
  LASTNAME  VARCHAR(255) NOT NULL,
  PRIMARY KEY(ID)
);

INSERT INTO USERS (ID, USERNAME, FIRSTNAME, LASTNAME) VALUES (-1, 'jdoe', 'John', 'Doe');
INSERT INTO USERS (ID, USERNAME, FIRSTNAME, LASTNAME) VALUES (-2, 'emuster', 'Erika', 'Mustermann'); 
